### ISSUE TITLE
Missing Readme File and Project Explanation

### ISSUE THREAD

**Issue by smrrazavian** [Rostamborn/MonkeyLang#1]
### Issue Description
I've noticed that the repository currently lacks a readme file, which makes it challenging for users like me to understand the purpose and functionality of the project. A readme file is crucial as it provides essential information for newcomers, outlining the project's objectives, functionalities, and instructions on how to run or use it.

### Suggested Action
I kindly request the repository owner to consider adding a readme file to the project. This readme file should include the following details:

1. **Project Overview:** Briefly explain the purpose and objectives of the project. What problem does it address or what features does it offer?

2. **Installation Instructions:** Provide a step-by-step guide to set up and run the project locally. Include any prerequisites, dependencies, and commands necessary for successful execution.

3. **Usage Guide:** Offer examples or explanations on how to utilize the project's features. If applicable, include code snippets to aid users in understanding the implementation.

4. **Contributing Guidelines (if applicable):** If the project is open to contributions, outline the process for submitting pull requests and collaborating with the community.

Adding a comprehensive readme file would greatly assist users like me in quickly getting started and would also encourage increased engagement and contributions from the community. Thank you for considering this request.

### Example Readme
Here's an example of what the contents of the README.md file might look like for this issue:

```markdown
# Project Name

## Overview
Briefly describe the purpose and goals of the project. Explain the problem it aims to solve or the functionality it provides.

## Table of Contents
- [Installation](#installation)
- [Usage](#usage)
- [Contributing](#contributing)
- [License](#license)

## Installation
Provide step-by-step instructions on how to set up and run the project locally. Include any prerequisites and dependencies that need to be installed.

```bash
$ git clone https://github.com/username/repository.git
$ cd repository
$ npm install   # or any other relevant commands
$ npm start     # or how to start the project

**Comment by Rostamborn** [comment]
chashm
